### ISSUE TITLE
Output must stay in the same window for OBS capture

### ISSUE THREAD

**Issue by SkullFire58** [MKeru/offhand-dialogue#3]
The output will need to remain in a consistent window so that OBS can easily keep track of it, the entire program could be the same window since the text boxes and output don't ever need to be displayed at the same time, or have two constant windows, whichever's easier. If sharing one window, important buttons can be kept off to the side at all times since we can crop them out in OBS.

**Comment by MKeru** [comment]
The form and all components are now fixed sizes. The panel containing inputs and final story panel are now scrollable.
